variable "vpc_name" {}
variable "vpc_cidr" {}
variable "public_subnet-1" {}
variable "public_subnet-2" {}
variable "private_subnet-1" {}
variable "private_subnet-2" {}
variable "imagename" {}
variable "key_name" {}
variable "instance_type" {}
variable "subnet-1" {}
variable "subnet-2" {}